### PR TITLE
Generated new seeds and recipes for RimCuisine2

### PR DESCRIPTION
**Pull request by Omegaice**
I wrote a script to parse out and generate data for RimCuisine2 which can be found [here](https://gist.github.com/Omegaice/0fd1ec3e3c24060df39a62b45bf552af#file-main-go). 

This PR imitates the old RimCuisine recipes with a fixed 4 items produces 3 seeds. I implemented a configurable option in the script to scale these values based on days worth of food (15 days worth required to produce 2 days worth extra) as I was trying to make it a little more challenging for myself.

### CODE REVIEW

**Comment by notfood** [comment]
Looks fine, I'll test it in game and get back to you

**Comment by Omegaice** [comment]
Turns out that this patch doesn't work fully. It fails for every biome specific plant because they are defined as two separate plants (one for the biome and one for the hydroponics) and the script I wrote only creates hydroponic versions of the seeds in that case. 

I don't think that this is solvable without changing the code of this mod to allow specifying a ground and a hydroponic plant recipe for each seed and add code to handle picking the correct one on job start.

**Comment by notfood** [comment]
Seeds Please already handles this situation with the `<sources>` tag

For example: https://github.com/notfood/RimWorld-SeedsPlease/blob/master/Defs/ThingDefs/Items_Seeds_Production.xml#L29-L31

**Comment by Omegaice** [comment]
Awesome, I will update the pull request later after testing this.

**Comment by Omegaice** [comment]
I have not tested these yet but it matches the example you linked. I also made them use any available texture and fixed some descriptions.

**Comment by Omegaice** [comment]
Ok, I have tested this quite a bit now and I think I got everything. The only thing I did not test is if the biome sensitivity of some of the plants works.

**Comment by notfood** [comment]
Isn't it inverted? Aren't the hydro the ones you can plant and the others are the wild?

**Comment by Omegaice** [comment]
Does it matter which is the plant and which is in source? I didn't notice any issues when testing.

**Comment by notfood** [comment]
Yeah, the plant that will grow is the one in <plant>, the ones in <source> will yield the seed.

**Comment by Omegaice** [comment]
Ok, I inverted the two and checked that I am still restricted to only things I have seeds for and they are used when sowing.

**Comment by notfood** [comment]
Also, if you only load RimCuisine core you get a lot of red errors. This needs to be split.

**Comment by notfood** [comment]
The names are incorrect, you can't name the seed "xxx plant", it must be "xxx seed".

**Comment by notfood** [comment]
Seems like the only difference between Normal and Hydro plants is the `<mustBeWildToSow>true</mustBeWildToSow>` tag which would restrict them in their proper biomes if they're outside hydrophonics.

SeedsPlease will work in any order in this case.

I'll be running my scripts now.

**Comment by Omegaice** [comment]
I am just fixing up the names and splitting the drug plants out. Should be done soon.

**Comment by notfood** [comment]
Alright. You will want to squash it all into a single commit when you are done, I'll be squashing it otherwise.

**Comment by Omegaice** [comment]
Separated the drugs out, changed the seed labels and squashed it. Let me know if there is anything else that is missing.

**Comment by notfood** [comment]
Alright, works fine. One last very small cosmetic detail, everything seems to be indented one more time unnecessarily,  two spaces before `<Defs>`. Can you fix that?

**Comment by Omegaice** [comment]
Fixed.

**Comment by notfood** [comment]
Cheers

**Comment by notfood** [comment]
For some reason your script missed hydroponic onion

**Comment by notfood** [comment]
Fixed and published to steam

**Comment by Omegaice** [comment]
> 
> 
> For some reason your script missed hydroponic onion

Did you check to make sure you had the latest version of RimCuisine2 Core? There used to be a hydroponic onion but it seemed to have been removed over the last day or so.

**Comment by notfood** [comment]
Huh... I'm running steam.

**Comment by notfood** [comment]
Even after restarting steam I am not getting an update.

**Comment by Omegaice** [comment]
Strange, I will check again tomorrow in case my mods are out of date for some reason. It used to be there and then I noticed an error when starting the game and found that it had been removed.

**Pull request merged**
